# latexindent configuration file
onlyOneBackUp: 1

defaultIndent: "  "

indentAfterHeadings:
  part:
    indentAfterThisHeading: 2
  chapter: 
    indentAfterThisHeading: 2
  section:
    indentAfterThisHeading: 2
  subsection:
    indentAfterThisHeading: 2
  subsection*:
    indentAfterThisHeading: 2
  subsubsection:
    indentAfterThisHeading: 2
  paragraph:
    indentAfterThisHeading: 2
  subparagraph:
    indentAfterThisHeading: 2

indentAfterItems:
  itemize: 2
  enumerate: 2
  description: 2
  list: 2

indentRules:
  myenvironment: "  "
  anotherenvironment: "    "
  chapter: "  "
  section: "  "

replacements:
  - amalgamate: 1
  -
    # Insert 1 half-width space before and after "="
    substitution: s/(?<!\+|\-)\h{0,}\=\h{0,}(?!\+|\-)/ \= /g
    lookForThis: 1
  -
    # Insert half-width space before the "\" in any command
    substitution: s/\h{0,}\\(?!=\{)(\S)/ \\$2/g
    lookForThis: 0
  -
    # Combine 2 or more "half-width spaces" into 1
    substitution: s/\h+/ /g
    lookForThis: 1
    when: before