name: Release

on:
  push:
    tags:
    - 'v*'
env:
  # Change this to the name of your LaTeX document
  FILENAME: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t latex_docker .devcontainer/

    - name: Compile LaTeX document
      run: docker run --rm -v $PWD:/workdir latex_docker latexmk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload compiled document to Release
      uses: softprops/action-gh-release@v1
      with:
          files: ${{ env.FILENAME }}.pdf